google/adk-docs

docs/tools/google-cloud-tools.md

Update dependencies, fix import. Remove function call that's missing a mandatory argument.

Fix code snippet in Toolbox section

---

docs/contributing-guide.md
docs/index.md
mkdocs.yml

Add Contributing guide to Github.io page

feat(contributing): add contributing guide

---

docs/deploy/cloud-run.md

fix: cloud run deployment instructions with gcloud

---

docs/tools/built-in-tools.md

update some limitations and techniques for built-in tools

fix: Update limitations and techniques for using built-in tools

---

docs/agents/multi-agents.md

Import for the AgentTool class was incorrect

Fixing AgentTool imports

---

docs/tools/google-cloud-tools.md

Update typos and code formatting of `google-cloud-tools.md`.

docs: update google-cloud-tools.md

---

docs/get-started/quickstart.md

Hi,
Just fixing 1 type: describe -> described.
See commit diff for all details
Didier

Update quickstart.md: fixing 1 typo

---

docs/deploy/gke.md
mkdocs.yml

add instruction for deploying to gke

---

docs/agents/models.md

Clarifies how to use ollama models with ADK litellm wrapper.

Update ollama related documentation

---

docs/tools/google-cloud-tools.md

[please merge this PR for me, on approval]

fix(google-cloud-tools): reword intro

---

examples/python/snippets/tools/function-tools/summarizer.py

It must fix this issue https://github.com/google/adk-python/issues/212

Fixed instruction for root agent to avoid summarization before passing text to summary agent

---

docs/tools/google-cloud-tools.md

Fixes https://github.com/google/adk-docs/issues/97

cloud-tool-render-issue

---

examples/python/snippets/agents/workflow-agents/loop_agent_doc_improv_agent.py

Fixes #66 
[kindly merge this PR for me]

fix(loop-agent): update max_iterations param

---

docs/get-started/quickstart-streaming.md

Multimodal inputs require specific supportedGenerationMethods to be included in the model details, bidiGenerateContent for audio/video, generateContent for text.

Clarify documentation on multimodal model support

---

docs/get-started/quickstart-streaming.md

A fix for: https://github.com/google/adk-python/issues/74

fix: Added the full directory structure for the custom streaming app.

---

mkdocs.yml

Add footer navigation (next, previous) pages for easy page scrolling

feat: add footer navigation

---

.github/header-checker-lint.yml

Add config file for header-checker-lint.yml to limit checking for python files

feat: add header-checker-lint.yml

---

docs/get-started/quickstart-streaming.md

Adding Vertex AI support to Quickstart (streaming)

fix: Quickstart (streaming): fix the SSL error for audio and video, and add Vertex AI support.

---

docs/tools/mcp-tools.md

fix: Add instruction for MCP tools with ADK web

fix: Update mcp-tools.md

---

examples/python/agent-samples/youtube-shorts-assistant/scriptwriter_instruction.txt

Thank you for https://www.youtube.com/watch?v=44C8u0CDtSo.
I found a typo in the instruction, so send this pull request.

fix: typo in youtube-shorts-assistant scriptwriter instruction

---

docs/agents/multi-agents.md

This PR is try to fix this issue for this example[1].
[1] https://google.github.io/adk-docs/agents/multi-agents/#b-llm-driven-delegation-agent-transfer
(.venv) user@xxxxx:~/abehsu/google_adk_explore$ uv run python /home/user/abehsu/google_adk_explore/progressive_weather_bot_agent/agent_transfer.py
Traceback (most recent call last):
File "/home/user/abehsu/google_adk_explore/progressive_weather_bot_agent/agent_transfer.py", line 72, in <module>
asyncio.run(execute_runner(
File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/home/user/abehsu/google_adk_explore/progressive_weather_bot_agent/agent_transfer.py", line 57, in …

docs: ancestor agent have to associate with a model.

---

docs/mcp/index.md
mkdocs.yml

Adding new MCP section. Is this the right way to add new section?

feat: add MCP section

---

docs/streaming/index.md
mkdocs.yml

As per the request on #166 , adding new Streaming section.

feat: Add Streaming section

---

docs/tools/function-tools.md
examples/python/snippets/tools/function-tools/func_tool.py

Docs improvement suggestion according to issue #210

feat: Docs improvement: FunctionTool 

---

docs/streaming/index.md
docs/streaming/streaming-tools.md

doc: add streaming tools guide.

---

docs/tools/built-in-tools.md

Improvement to the Limitation section of the built-in tools documentation to make it more clear.
Discussed with @hangfei in the thread below:
https://github.com/google/adk-python/issues/514#issuecomment-2848385620

docs: update built-in-tools.md to clarify tool limitations

---

docs/get-started/quickstart-streaming.md

- With 0.4.0, the tool name has changed to google_search
- As of today, gemini-2.0-flash-exp is the workable model with Streaming for ADK that is soon to be replaced with gemini-2.0-flash-live-001.

fix: Fixed the google search tool name and model name

---

docs/tools/mcp-tools.md

Missing the import from contextlib
Also remove two spurious arguments to SseServerParams

fix: Minor cleanup to FastMCP sample

---

docs/agents/workflow-agents/sequential-agents.md

This PR fixes #248 where the redundant only is removed

fix: redundant only's in sequential agent

---

docs/community.md
examples/python/notebooks/shop_agent.ipynb

Add e-commerce recommendation notebook intro

feat: Add e-commerce recommendation notebook intro

---

docs/streaming/index.md
mkdocs.yml

add Streaming video to the doc

fix: add Streaming video to the doc

---

docs/stylesheets/custom.css
mkdocs.yml
overrides/partials/source.html

Showing the fork/stars stats is a bit tricky so hiding them for now

feat: Show adk-java repo in the header

---

docs/deploy/index.md

Adding link to GKE Deploy doc in https://google.github.io/adk-docs/deploy/

Add gke link in deploy index.md

---

docs/streaming/custom-streaming.md
examples/python/snippets/streaming/adk-streaming/app/main.py

fix: to support adk 1.0.0

---

docs/streaming/custom-streaming-ws.md
docs/streaming/custom-streaming.md
docs/streaming/index.md
examples/python/snippets/streaming/adk-streaming-ws/app/google_search_agent/__init__.py
examples/python/snippets/streaming/adk-streaming-ws/app/google_search_agent/agent.py
examples/python/snippets/streaming/adk-streaming-ws/app/main.py
examples/python/snippets/streaming/adk-streaming-ws/app/static/index.html
examples/python/snippets/streaming/adk-streaming-ws/app/static/js/app.js
examples/python/snippets/streaming/adk-streaming-ws/app/static/js/audio-player.js
examples/python/snippets/streaming/adk-streaming-ws/app/static/js/audio-recorder.js
examples/python/snippets/streaming/adk-streaming-ws/app/static/js/pcm-player-processor.js
examples/python/snippets/streaming/adk-streaming-ws/app/static/js/pcm-recorder-processor.js
examples/python/snippets/streaming/adk-streaming/app/main.py
mkdocs.yml

fix: add SSE Streaming sample

---

docs/streaming/custom-streaming-ws.md
docs/streaming/custom-streaming.md
examples/python/snippets/streaming/adk-streaming-ws/app/google_search_agent/agent.py
examples/python/snippets/streaming/adk-streaming/app/google_search_agent/agent.py

fix: Added SSL CERT setting and code snippets

fix: Added SSL CERT setting and code snippets

---

docs/context/index.md

Its not available in google.adk.agents and moved to google.adk.agents.invocation_context

[fix] changed the import for InvocationContext

---

docs/get-started/installation.md

fix pom dependencies symbol missing

Update installation.md to fix java pom dependencies symbol missing

---

docs/get-started/streaming/quickstart-streaming.md

remove redundant model information which is covered in earlier sections.

doc: Update quickstart-streaming.md

---

.github/workflows/link-checker.yaml
.github/workflows/publish-docs.yaml
requirements.txt

Adds a link checker to verify external links. Note that internal links are already checked as part of the mkdocs build.
Uses:
- https://github.com/byrnereese/linkchecker-mkdocs
- https://github.com/marketplace/actions/mkdocs-link-check

feat: Add link checker action

---

docs/observability/phoenix.md

Hi, I’m Sanjana from the Arize Phoenix team.
We recently made some updates to Phoenix that required a small adjustment in the documentation here. This PR updates a few lines of code in the connection instructions to align with the latest Phoenix changes.
Please let me know if there are any adjustments needed. Thank you!

docs: updating Phoenix connection instructions

---

docs/deploy/gke.md

- [adk deploy gke](https://github.com/google/adk-python/pull/1607) needs to get merged.
- need to show this feature is coming soon and not yet here.

add coming soon text for gke adk deploy section

---

docs/context/index.md

- Issue: https://github.com/google/adk-docs/issues/540
- Also fixed parallel issue with CallbackContext

fix(docs): Fixing code example problem for ReadonlyContext

---

docs/tools/google-cloud-tools.md

Added Python ADK instructions in the Application Integration Tools section.

docs(adk): add Python ADK instructions to Application Integration Tools in google-cloud-tools.md

---

docs/a2a/index.md

Fixes incorrect link to A2A website.

fix(link): A2A site

---

docs/streaming/index.md

fix(docs): adding extra information and context to bidi streaming.

---

docs/get-started/streaming/quickstart-streaming.md

fix: adding windows version of command

---

examples/python/agent-samples/youtube-shorts-assistant/agent.py

Fixes #176 
Use AgentTool for subagents

fix: Update agent.py

---

docs/sessions/state.md

Included instruction to handle keys that may not be present.

docs: key templating with keys that may not be present

---

llms-full.txt

Fix a link that need to be escaped in markdown

---

.github/workflows/feature-matrix-updater.yaml

Remove adk-docs-features directory after moving files.

fix: Update feature matrix updater workflow
