docs/get-started/local-testing.md

It fixes the deployment broken links in the getting started page of the guide.

Fixes deployment broken links

---

docs/get-started/tutorial.md

social-link-colab-tutorial

---

docs/index.md

Fix Contribute link on docs landing page

---

docs/contributing-guide.md

Add information on Github discussions tab in adk-python to the contributing guide.

update(contributing-guide): add community discussion info

---

examples/python/snippets/get-started/multi_tool_agent/agent.py

Use second-person (you) instead of first-person (I) in the agent instruction.

Update Agent instruction in quick-start example

---

docs/deploy/index.md

minor typo fix in `docs/deploy/index.md`.

docs: typo in deploy doc

---

docs/deploy/cloud-run.md

Fixes #52 
- Add port to gcloud run deploy command
- Add localhost:8000 to allowed origins
- Update agent_dir_name to agent_dir in note.

[WIP] gcloud cli instruction for cloud run deploy

---

docs/get-started/local-testing.md

Suggesting adding a `third-party test intergrations` to the `local-testing.md`. The open-source LLM testing and observability toolkit natively supports ADK following a [feature request on adk-python](https://github.com/google/adk-python/issues/48) this was released publicly by Opik team yesterday on build [1.7.2](https://github.com/comet-ml/opik/releases/tag/1.7.2) following the ADK annoucement.
The implementation of the callback and tracing of ADK on Opik supports all uses from costs to tool usage (_see screenshots below_).
Opik the fastest growing agent framework and llm-agnostic tracing solution that has been widley adopted. Happy for maintainers to suggest alternatives to documentation but felt its best suited within the testing/debuging section rather than opening a new page like …

docs: added third-party testing solutions

---

.github/workflows/publish-docs.yaml
docs/get-started/quickstart.md
docs/get-started/testing.md
mkdocs.yml
requirements.txt

This PR updates the content and applies formatting fixes to the testing page and expands its scope to include local and remote testing solutions. In the future, we can consider a separate guide that covers tools and workflows related to monitoring, tracing, and observability.
- Rename local testing page to testing
- Add `mkdocs-redirects` pkg and config, add redirect from old page to new page
- Simplify ToC for readability

Updates and formatting fixes to Testing page

---

examples/python/snippets/tools/function-tools/func_tool.py

Changed the agent's description from second-person (you) to third-person (this agent).
I also fixed a couple of grammatical errors in the agent's instructions.

Use third-person (this agent) instead of second-person (you) in the agent description

---

docs/contributing-guide.md

The original link was point to the site itself rather than the git repository.

fix: Update google/adk-docs repository link

---

docs/get-started/quickstart.md

Removing the first one will help users understand.

fix: The copy/paste is duplicated in quickstart.md

---

docs/tools/google-cloud-tools.md

This PR improves the readability and structure of the Google Cloud Tools documentation page.
Fixes https://github.com/google/adk-python/issues/146.

Update headings and links on Google Cloud Tools page

---

docs/guides/responsible-agents.md

Hi,
Just fixing  typo for verb to constrain spelled with superfluous 't'.
See commit diff for details.
Didier

Update responsible-agents.md: fixing typo on constrain verb

---

docs/community.md
docs/get-started/quickstart.md
mkdocs.yml

Closes #80. Creates a community page with a link to the translated ADK docs page mentioned in #79, and opens up the opportunity for us to showcase the latest community resources for ADK!

Initial commit of Community Resources page

---

overrides/main.html

Followup PR to #84 and #85 to fix the URL path to the ADK social media preview card image.

Fix social cards - Update image URL

---

docs/deploy/cloud-run.md

Hi, 'in on' seems redundant: see commit diff.
I chose one ('in')  and removed the other ('on')
Didier

Update cloud-run.md: redundant words

---

examples/python/snippets/tools/function-tools/summarizer.py

There was a mistake in the Agent-as-a-tool example in the documentation. There should be `root_agent` passed in the Runner instead of `summary_agent` which i fixed in this PR.

Update docs to add root agent instead of summary agent

---

mkdocs.yml

Closes #92 
Adding material toc - permalinks to docs. 
Enables permalinks to all headings - we can change to an anchor or something fancier if you wish later on.

Adds permalinks to headings - update mkdocs.yml

---

docs/get-started/quickstart-streaming.md

Typo in print output, as use uses "AGNET" instead of "AGENT"

Typo in print output

---

docs/sessions/memory.md

mainly the content is missing role info, while adk will filter out all those content without role.
see https://github.com/google/adk-python/issues/244

fix: Add user role in querying memory example

---

docs/evaluate/index.md

Thanks to great docs.
I first read https://google.github.io/adk-docs/get-started/quickstart/#__init__py ,
then read evaluation doc and I found that `init.py` is wired.
Refer to https://github.com/google/adk-python/blob/v0.1.0/src/google/adk/cli/cli_tools_click.py#L111
```
The path to the __init__.py file that contains a
```

docs: Fix init.py -> __init__.py

---

docs/agents/custom-agents.md

Update the variable name in `docs/agents/custom-agents.md`.
* Change the variable name to `GEMINI_2_FLASH` on line 114 to maintain consistency with example's code

fix: variable name in custom agents documentation

---

docs/get-started/quickstart-streaming.md

Issue:
A typo was identified in the file **get-started/quickstart-streaming.md**. In the demo streaming agent example, documentation mentions to select `**basic_search_agent**` from agent drop-down menu. However, this agent name does not show up and `**google_search_agent**` needs to be selected instead as only the directory name shows up in the drop-down menu.
Fix:
The typographical error of agent name has been corrected in get-started/quickstart-streaming.md file. This change improves the accuracy and readability of the project's documentation.
PFB screenshot for reference:

Docs: Quickstart (streaming): Correct the agent name in drop-down menu

---

docs/agents/workflow-agents/parallel-agents.md
examples/python/snippets/agents/workflow-agents/parallel_agent_web_research.py

— Adding detail instructions in the sample code to run the sample code with choice of interface. Users can now choose the method and follow instructions given in the sample .py file. 
— It clarifies that user would need to change the main agent name to `root_agent` if they are running it in `adk web`, `adk cli` or `adk api_server`. 
— Uses `InMemoryRunner` for notebooks/script.

parallel-agent-code-fix

---

docs/sessions/session.md

sqlalchemy is already installed and this package does not exist per https://github.com/google/adk-python/pull/43
Fixes https://github.com/google/adk-python/issues/25

Remove reference to  pip install google-adk[database]

---

mkdocs.yml

Followup to #143 that fixes the redirect page / URL for the old tutorial page.

fix: Change redirect for old tutorial page

---

docs/get-started/index.md
docs/get-started/quickstart.md
docs/index.md
docs/tutorials/index.md
mkdocs.yml

A followup PR to #151 to add redirects for Safety and Security page. Also fixed links to tutorial page.

fix: Update redirects and links for Safety and Security page

---

CONTRIBUTING.md

fix: add missing .txt within "Install dependencies" step

fix: add missing .txt within "Install dependencies" step

---

docs/agents/workflow-agents/parallel-agents.md

fix: the ParallelAgent execute run_async instead of run() base on this line [1].
[1]https://github.com/google/adk-python/blob/main/src/google/adk/agents/parallel_agent.py#L94

fix: the ParallelAgent execute run_async instead of run() 

---

docs/tools/mcp-tools.md

Fixes URLs to images on MCP tools page.

fix: Update links to screenshots on MCP tools page

---

docs/get-started/quickstart-streaming.md

Fix error  "cannot import name 'google_search' from 'google.adk.tools'"

fix: Update quickstart-streaming.md with correct Google Search tool import

---

docs/tools/google-cloud-tools.md

Clearing up that the tools for `ApplicationIntegrationToolset` should be added
to `tools.py` as this is not explicitly mentioned.
Can only tell this is where to put them by the import in the subsequent
section having the import as `from .tools import ...`
Also fixing rendering of `__init__.py`

chore: update google-cloud-tools.md

---

docs/get-started/quickstart-streaming.md

This PR fixes #216 
fixed the google search import from `built_in_google_search` to  `google_search`

fix: google_search import issue

---

docs/tools/mcp-tools.md

**Describe the bug**
In the "Set up ADK" section under Tools > MCP Tools > Prerequisites, the 'setup' markdown link is missing its URL, resulting in an empty link.
**To Reproduce**
1. Go to: https://google.github.io/adk-docs/tools/mcp-tools/#what-is-model-context-protocol-mcp
2. Scroll to the "Set up ADK" section
3. The' [setup] ()' link is missing its URL.
**Expected behavior**
The link should direct users to the proper ADK setup instructions.
*Screenshots*
**Versions**
- OS: Windows 11
- ADK version: 0.5.0
- Python version: 3.9.0
**Additional context**
The fix adds the correct link to the setup guide in place of the empty placeholder.

fix: Correct broken [setup]() link in MCP Tools documentation

---

docs/tools/google-cloud-tools.md

This change is dependent on https://github.com/google/adk-python/pull/763 getting merged and released.
Updating MCP Toolbox for Databases section to now showcase lightweight `toolbox-core` import and guidance to use it directly over the soon to be deleted `ToolboxTool`
```python
from google.adk.agents import Agent
from toolbox_core import ToolboxSyncClient
toolbox = ToolboxSyncClient("http://127.0.0.1:5000")
toolbox_tools = toolbox.load_toolset("my-toolset")
root_agent = Agent(
model="gemini-2.0-flash",
name="root_agent",
instruction=agent_instruction,
tools=toolbox_tools,
)
```

docs: update MCP Toolbox docs

---

docs/artifacts/index.md

As of ADK 1.0.0, the artifact service methods are now `async` and should use `await`
[ADK Python artifact service code showing async](https://github.com/google/adk-python/blob/a2263b18083fccd176b3ed61c368a65d9b7efde4/src/google/adk/artifacts/in_memory_artifact_service.py#L83)
```python
artifact = tool_context.load_artifact(filename=filename)
```
```python
artifact = await tool_context.load_artifact(filename=filename)
```

docs: update Python artifact docs to use async/await

---

docs/tutorials/agent-team.md

Fixes this block that should be bullet points:

docs: add line break to render bullet points in agent-team.md

---

docs/get-started/streaming/quickstart-streaming.md

Removed the incorrect instruction to copy code into a non-existent `main.py` file. Now it only mentions `__init__.py`, matching the ADK streaming guide and avoiding confusion during setup.

fix: remove incorrect reference to main.py in get-started streaming guide

---

docs/agents/models.md
docs/get-started/quickstart.md
docs/get-started/streaming/quickstart-streaming.md
docs/sessions/session.md
docs/tools/mcp-tools.md

…flicts, we are doing all those small changes in this PR. Each changes are listed below:
- #254 docs/sessions/session.md -> …part of session object's identification. In the session object identification description, it was unclear (for first time readers), what exactly is id, and app_name and how they are different. Added some examples according to my own understanding. Please change accordingly if you feel so. Thanks.
- #252 Multiple files: quickstart-streaming.md,  quickstart.md, mcp-tools.md add an option in the CLI to enable or disable the reload feature. So users(esp. windows) can disable this if they come across the '_make_subprocess_transport NotImplementedError' bug on windows.
- #179 docs/agents/models.md -> Add Windows Encoding Note for LiteLLM When using ADK agents with LiteLlm …

[PR fixes]This PR is fixing multiple old PRs due to merge conflicts.

---

docs/streaming/index.md

This PR corrects a duplicated typo of the word "streaming" in `docs/streaming/index.md`.
The word "streaming" was written incorrectly twice in close proximity.

docs(streaming): correct duplicated typo of 'streaming'

---

docs/tutorials/agent-team.md

This addresses a bug in the session inspection logic where `final_session.state.as_dict()` was being called. Since `final_session.state` is already a Python dictionary, calling `.as_dict()` results in:
```
AttributeError: 'dict' object has no attribute 'as_dict'
```
Changes Made:
- Removed the `.as_dict()` call.
Impact:
- Fixes the runtime error and ensures correct behavior when inspecting session state.

fix: remove .as_dict() usage from final session state logging

---

docs/tutorials/agent-team.md

This PR adds a note at the beginning of the tutorial documentation to clarify that the tutorial requires `adk >= 1.0.0`. 
This helps prevent compatibility issues, as older versions may not support some async methods used in the examples.

docs: specify ADK version requirement for tutorial compatibility

---

docs/evaluate/index.md

The example code for Evaluation - PyTest was incorrect.
Since the evaluation functions were updated to async in [this commit](https://github.com/google/adk-python/commit/e7d9cf359a082904dfe1bcacbfebedfe73a64768), the PyTest example code should be updated.

fix(docs): Fix broken pytest example code

---

docs/streaming/index.md

fix: missing links and formatting on streaming/index.md

fix: missing links and formatting on streaming/index.md

---

docs/sessions/memory.md

Fixes: #511
This PR addresses a gap in the documentation for `InMemoryMemoryService` where the code example was incomplete.
Previously, the example defined both an `InfoCaptureAgent` and a `MemoryRecallAgent` but only demonstrated a single turn where information was stored in memory. It completely omitted the crucial step of retrieving that information, leaving users without a clear, functional example of the full memory lifecycle.
This change updates the code snippet by adding a 'Turn 2'. In this second turn, a new `Runner` is configured with the `MemoryRecallAgent` to ask a question that requires memory access. The updated example now successfully demonstrates both storing and retrieving information, providing a complete and runnable guide for developers.

docs: complete in-memory memory example with retrieval step

---

docs/tools/function-tools.md

This PR addresses outdated and incorrect documentation for `FunctionTool` parameter handling, closing issues #473, #481, and #210.
The existing documentation incorrectly advises against using default values for parameters, a feature that is fully supported by the ADK framework. This has caused confusion and limited developers' ability to define flexible tools.
This change:
- Removes the inaccurate statement about default parameters.
- Completely overhauls the 'Parameters' section in `function-tools.md` into a new, structured guide on defining function signatures.
- Provides clear, distinct code examples for required parameters, optional parameters with default values, and optional parameters using `typing.Optional`.
- Clarifies that variadic arguments (`*args`, `**kwargs`) are ignored for …

docs: clarify FunctionTool parameter handling and add examples

---

docs/tools/mcp-tools.md

This PR changes:
`StdioServerParameters` -> `StdioConnectionParams`
`SseServerParams` -> `SseConnectionParams`
For `StdioServerParameters`, the recommendation is to use:
`StdioServerParameters is not recommended. Please use StdioConnectionParams.`
Also, `SseServerParams` have been completely removed in favor of `SseConnectionParams` in this commit: https://github.com/google/adk-python/commit/54367dcc567a2b00e80368ea753a4fc0550e5b57

docs: change ServerParams to ConnectionParams

---

examples/python/snippets/agents/llm-agent/capital_agent.py

The example without this fix fails with an error:
```
ValueError: Session not found: session_tool_agent_xyz
```

fix: llm-agents capital_agent.py example failing due to missing awaits

---

docs/tools/mcp-tools.md

This PR fixes the examples of locally hosted mcp servers. The `StdioConnectionParams` requires `server_params` to provide the command for starting the mcp server.

fix: correct the examples of locally hosted mcp servers

---

examples/python/snippets/streaming/adk-streaming-ws/app/main.py
examples/python/snippets/streaming/adk-streaming-ws/app/requirements.txt

fix: upgraded to adk 1.9.0 and removed unnecessary infinite loop

fix: upgraded to adk 1.9.0 and removed unnecessary infinite loop

---

.link-checker-config.json

Updating the link checker to add cloud console and a2aprotocol links as valid.

fix(docs): Link checker config update

---

CONTRIBUTING.md
docs/a2a/quickstart-consuming.md
docs/a2a/quickstart-exposing.md
docs/agents/custom-agents.md
docs/agents/multi-agents.md
docs/callbacks/design-patterns-and-best-practices.md
docs/contributing-guide.md
docs/get-started/quickstart.md
docs/get-started/streaming/quickstart-streaming.md
docs/grounding/google_search_grounding.md
docs/grounding/vertex_ai_search_grounding.md
docs/observability/arize-ax.md
docs/observability/phoenix.md
docs/streaming/custom-streaming-ws.md
docs/streaming/custom-streaming.md
docs/streaming/dev-guide/part1.md

feat: adding heading identifier to improve link ability

---

docs/tools/index.md

The `lookup_order_status` example in the tool documentation was using the `status` field to represent both the tool's execution outcome and the business-level order status. This is ambiguous and can be confusing for the LLM.
This change refactors the example to use a dedicated `status` field for the execution outcome (`success`/`error`) and nests the order-specific data in a separate `order` dictionary. This aligns with best practices for tool design and improves clarity.
Fixes #530

docs: Clarify tool status field in example

---

examples/python/snippets/streaming/adk-streaming-ws/app/main.py
examples/python/snippets/tools/built-in-tools/code_execution.py

Fixed spelling and syntax errors in Python examples

fix: correct syntax error and typo in Python examples

---

docs/api-reference/agentconfig/index.html

fix: add a stub page for the Agent Config API docs

fix: add a stub index page for the Agent Config API docs

---

.github/workflows/publish-docs.yaml
mkdocs.yml

The CICD tests responsible for generating static pages are failing to add the necessary keys to the site. The current settings proved unhelpful, so they have been cleared.
Removed changes added in https://github.com/google/adk-docs/pull/556 and https://github.com/google/adk-docs/pull/580

Chore: Cleaned up the (failed) Google Analytics code.

---

docs/tools/google-cloud-tools.md

This PR removes a redundant sentence from the `ApplicationIntegrationToolset` documentation.
The following sentence appeared twice:
　　Application Integration Toolset supports `auth_scheme` and `auth_credential` for dynamic OAuth2 authentication for Integration Connectors.
The first instance was at the beginning of the section and felt out of context. The second instance correctly introduces the code example for dynamic OAuth2.
By removing the first, redundant sentence, the document becomes clearer and easier to read.

docs: remove redundant sentence for improved clarity

---

docs/tools/built-in-tools.md

This pull request addresses item #3 of issue #689, expanding the documentation for the `GkeCodeExecutor`.

Update ADK doc according to issue #689 - 3

---

docs/tools/google-cloud-tools.md

Fixes #630.
- Remove link to non-public Google doc, point to install page instead
- Cleanup redundant Python/Java selectors for common steps
- Other formatting fixes and cleanup

fix: Remove link and other cleanup in Application Integration Tools section

---

.link-checker-config.json

This PR adds `^https://www.gnu.org/` to the markdown-link-check ignore list. Links to this site are causing the link checker CI job to timeout or fail due to server flakiness. After this is merged, the [link checker GH action](https://github.com/google/adk-docs/actions/workflows/link-checker.yaml) should resume working as expected.

ci: Add site to markdown link checker ignore list
